package com.kg.code.common.mapper.enums;

public class SQL {
    public static final String QUERY_TABLE_FILED_SQL_1 = "SELECT COLUMN_NAME, DATA_TYPE, COLUMN_COMMENT, COLUMN_KEY, EXTRA FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = '";
    public static final String QUERY_TABLE_FILED_SQL_2 = "' AND TABLE_SCHEMA = ( SELECT DATABASE ()) ORDER BY ORDINAL_POSITION";
    public static final String QUERY_TABLE_SQL = "SELECT TABLE_NAME, TABLE_COMMENT FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA=(SELECT DATABASE())";
}
